# version: '2'
# services:
#   php:
#     image: yiisoftware/yii2-php:7.4-apache
#     volumes:
#       - ~/.composer-docker/cache:/root/.composer/cache:delegated
#       - ./:/app:delegated
#     ports:
#       - '8000:80'


version: '3.8'
services:
  yii2-app:
    image: yourdockerhubusername/yii2-app:latest
    deploy:
      replicas: 1
    networks:
      - web
    # ports:
    #   - "8000:80"
networks:
  web:
    external: true
